baseURL = "http://hugo-local.s3-website-us-east-1.amazonaws.com"
languageCode = 'en-us'
title = 'Ahmed Gharib Hugo Website'
theme = "ananke"

[[deployment.targets]]
name = "awsbucket"
URL = "s3://hugo-local/?region=us-east-1"